const actionTypes = {
    GET_ARTICULOS_REQUESTED: 'GET_ARTICULOS_REQUESTED',
    GET_ARTICULOS_SUCCESS: 'GET_ARTICULOS_SUCCESS',
    GET_ARTICULOS_FAILED: 'GET_ARTICULOS_FAILED',
  
    CREATE_ARTICULOS_REQUESTED: 'CREATE_ARTICULOS_REQUESTED',
    CREATE_ARTICULOS_SUCCESS: 'CREATE_ARTICULOS_SUCCESS',
    CREATE_ARTICULOS_FAILED: 'CREATE_ARTICULOS_FAILED',
    
    DELETE_ARTICULOS_REQUESTED: 'DELETE_ARTICULOS_REQUESTED',
    DELETE_ARTICULOS_SUCCESS: 'DELETE_ARTICULOS_SUCCESS',
    DELETE_ARTICULOS_FAILED: 'DELETE_ARTICULOS_FAILED', 
    
    UPDATE_ARTICULOS_REQUESTED: 'UPDATE_ARTICULOS_REQUESTED',
    UPDATE_ARTICULOS_SUCCESS: 'UPDATE_ARTICULOS_SUCCESS',
    UPDATE_ARTICULOS_FAILED: 'UPDATE_ARTICULOS_FAILED',
  
    GET_ARTICULOS_BYID_REQUESTED: 'GET_ARTICULOS_BYID_REQUESTED',
    GET_ARTICULOS_BYID_SUCCESS: 'GET_ARTICULOS_BYID_SUCCESS',
    GET_ARTICULOS_BYID_FAILED: 'GET_ARTICULOS_BYID_FAILED',
  };
  
  export default actionTypes;